### PR TITLE
Update to remove T_DATA allocation function warning

### PR DESCRIPTION
**Pull request by gravatite**
Under Ruby 3.2 and newer, these warnings are generated: "warning: undefining the allocator of T_DATA class Shapelib::Point"

This change to Ruby is discussed here: https://bugs.ruby-lang.org/issues/18007

In that thread, Matz expresses that this should be an error, but they are taking the warning approach to allow for transition time for gem authors.

Other than this warning, the shapelib gem still works fine.  Our team is using it for our work on both ShadowCam and the Lunar Reconnaissance Orbiter Camera.  Thank you for maintaining this gem!

### CODE REVIEW

**Comment by mperham** [comment]
I literally don't even remember what I used this gem for. Would you like to be added as a maintainer of this repo?

**Comment by gravatite** [comment]
What would that entail? A colleague and I maintain about a dozen unreleased gems, some compiled and some pure ruby (we host them internally for our own systems/software), but I'm not familiar with the "official" RubyGems requirements or procedures. We do actively use the Shapelib gem on a handful of different versions of Ruby, so we're happy to serve as a "canary in the mineshaft" for Ruby API changes like this one.

**Comment by mperham** [comment]
Basically it's dealing with any issues/PRs which come in, approximately one every 14 years (😂), and running `rake release` to push any new version to rubygems.org. If you'll pardon the expression, it's not rocket surgery. I had completely forgotten this gem even existed and don't even recall what I used it for.

There's definitely some light Rakefile maintenance that could be useful to modernize the gem to the 2020s. Personally I would remove Jeweler, integrate Bundler's gem tasks instead and upgrade rake-compiler to a recent version but as the only known user, I'd let you set the technical direction.

**Comment by gravatite** [comment]
Sure, that's doable.  One issue in 14 years is a fairly easy level of commitment, especially considering it was my PR. 🙃  I've never used jeweler before, so I'm not opposed to pulling it out.

**Pull request merged**
